    name: Keep Streamlit App Alive

    on:
      schedule:
        - cron: '0 */10 * * *' # Runs every 10 hrs
      workflow_dispatch: 

    jobs:
      empty-push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Create empty commit
            run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git commit --allow-empty -m "Keep Streamlit app alive"
              git push
